services:
  backend:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
        - node_modules_backend:/app/node_modules
        - ./api:/app
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
        - node_modules_frontend:/app/node_modules
        - ./client:/app
volumes:
  node_modules_frontend:
  node_modules_backend: