version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"  # For testing only, not needed in production
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "80:80"      # This is the main entry point
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: